### ISSUE TITLE
Font is all weird on Mac and iPhone. PC and Android is normal

### ISSUE THREAD

**Issue by yofu1234** [joshbuchea/awesome-app-landing-page#7] opened 2016-07-24 22:49 UTC
![13840599_10153743283449117_345367437_o](https://cloud.githubusercontent.com/assets/12259153/17087039/d9cad3fc-51ce-11e6-8669-1a444c2cfa68.jpg)
![13838165_10153743281419117_1381744170_o](https://cloud.githubusercontent.com/assets/12259153/17087058/257f74a6-51cf-11e6-96ca-1293c836b214.png)
^What it loooks like on Mac and iPhones.

What its supposed to look like:
![2016-07-24_1840](https://cloud.githubusercontent.com/assets/12259153/17087066/41df2d30-51cf-11e6-90b6-881eb3bc0a68.png)

^I don't know why the description font is all messed up. I'm using the default fonts that Macs and PCs have.

**Comment by joshbuchea** [comment] 2016-07-25 04:05
¯_(ツ)_/¯ what font are you using?

**Comment by yofu1234** [comment] 2016-07-25 20:44
I'm using the same fonts as you are. 
Which is why I opened up this issue.

**Comment by joshbuchea** [comment] 2016-07-25 22:55
Change the `font-weight` value on `.marketing-desc` to `500`. It's currently set to `100`.

**Comment by yofu1234** [comment] 2016-07-28 16:33
Changed. I think its fixed!

**Comment by joshbuchea** [comment] 2016-07-28 18:26
@yofu1234 it appears this issue may have been resolved. I prefer contributors have an opportunity to close their own issues. If you feel this issue is resolved, would you mind closing it? If the issue is not resolved or the issue needs some clarification, I'm happy to discuss. Thanks!

**Closed as completed** 2016-07-28 23:15 UTC
